### ISSUE TITLE
Adventures of Batman & Robin, The (USA).md first music track has buzzing

### ISSUE THREAD

**Issue by benderscruffy** [jsgroth/jgenesis#108]
got o options then music test and choose the first track
let it run through and you will hear a buzzing sound

**Comment by jsgroth** [comment]
Was this tested with v0.7.2 or a later build? There are a few currently-unreleased improvements to Genesis audio quality:
* f5caa8bfc6c3131f59c77e11e4ce11c2db9d99ee: Fixes a bug where setting the PSG noise channel's period to 0 would produce cracking/popping instead of high-frequency white noise
* 616ea55c79df9e6c0a7a441f9f9cc9b2bf547a5a: Adds emulation for the YM2612 "ladder effect"
* eb57536fd05e70a3eb0aab04cf25b13ec2816928: Much more aggressive low-pass filter for resampling PSG audio output
* 7e5b7d605966e9f7c99e9701a304fab5bcddbf93: Much more aggressive low-pass filter for resampling YM2612 audio output

If this was in v0.7.2 then 7e5b7d605966e9f7c99e9701a304fab5bcddbf93 might fix this, it fixed buzzing/popping in some other games I was testing and this song sounds much worse in general if I revert that specific change.

**Comment by benderscruffy** [comment]
was in 0.7.2
