### ISSUE TITLE
automatic nightly builds

### ISSUE THREAD

**Issue by benderscruffy** [jsgroth/jgenesis#114]
so we dont have to wait for an offical release

**Comment by jsgroth** [comment]
I have GitHub Actions configured to automatically compile release builds on every commit and upload them as workflow arfifacts, e.g. this is currently the latest build:
https://github.com/jsgroth/jgenesis/actions/runs/9688737541

I wouldn't recommend these for general use but they're useful if you want to test whether a bug has been fixed since the last release.

These builds are currently only downloadable while logged in to GitHub but I could figure out a way to make them available elsewhere if needed.

**Comment by jsgroth** [comment]
Closing this, please open another issue if nightly builds are needed in a different format/location
