### ISSUE TITLE
Demons of Asteborg (World) (En,Fr,De,Es,It,Pt-BR) (v1.1) (Demo 5) (2021-09-13) (Aftermarket) (Unl).md messed up graphics and black screen after intro

### ISSUE THREAD

**Issue by benderscruffy** [jsgroth/jgenesis#115]

**Comment by jsgroth** [comment]
Based on [this video](https://www.youtube.com/watch?v=5RrHYRL1FPg) linked from the developer's website, this demo requires the bank-switching Super Street Fighter 2 mapper (not surprising since it has almost 15MB of ROM), but the system string in the header is "SEGA DOA" instead of the "SEGA SSF" string that causes most emulators to enable the SSF2 mapper. Enabling the SSF2 mapper for "SEGA DOA" in addition to "SEGA SSF" will fix this.
