### ISSUE TITLE
YETI3D-32X.bin crashes out the emulator

### ISSUE THREAD

**Issue by benderscruffy** [jsgroth/jgenesis#121]
[YETI3D-32X.zip](https://github.com/user-attachments/files/16026500/YETI3D-32X.zip)

**Comment by jsgroth** [comment]
This demo depends on the 32X hardware being present, although I don't see anything in the cartridge header that the emulator could use to unambiguously determine that this requires 32X rather than standalone Genesis.

The crashing has been fixed by changes to map the address ranges that 32X uses ($800000-$9FFFFF and $A15000-$A153FF). On master this demo hangs at a black screen, which is expected behavior if the 32X hardware is not present.

If I force the emulator to use the 32X core via the CLI then this demo seems to work (the glitchy line at the top is there on actual hardware as well):

![yeti](https://github.com/jsgroth/jgenesis/assets/1137683/394efecb-fbcb-435d-854f-f5da8316b738)

There is currently no way to force a specific core via the GUI however, so that's something I'll need to add for files like this where the extension and the header aren't enough to automatically determine which core use.

**Comment by jsgroth** [comment]
The v0.8.0 release adds a GUI option to forcibly open this demo using the 32X core, and it seems to work as expected in 32X mode
