### ISSUE TITLE
Another World (Europe).md flashing top of the screen 

### ISSUE THREAD

**Issue by benderscruffy** [jsgroth/jgenesis#122]

**Comment by jsgroth** [comment]
This is caused by the emulator incorrectly defaulting to NTSC mode for this game when it depends on PAL video timings, specifically the fact that PAL has 51 additional lines during VBlank. It unconventially has the ASCII string "EUROPE" in the region section of the cartridge header and the emulator interprets the 'U' there as meaning the game supports NTSC/U, which it clearly does not.
