### ISSUE TITLE
Tyrants - Fight Through Time (USA).md nothing but a black screen

### ISSUE THREAD

**Issue by benderscruffy** [jsgroth/jgenesis#127]

**Comment by jsgroth** [comment]
This seems to be related to the hardware quirk that Sesame Street: Counting Cafe depends on (#119).

It's in a loop polling the VDP status register's VINT flag and it expects to read 1 at least once, which can only happen if the VINT flag reads 1 slightly before the 68000 handles the interrupt. In actual hardware this works probably because of how the sub-instruction timings line up, plus the INT6 signal from the VDP being slightly delayed.

Sub-instruction 68000 timing and VDP synchronization would probably fix this more accurately, but in lieu of that I can fix this by making the VINT flag read 1 a few cycles before the VDP raises the interrupt.
