### ISSUE TITLE
[FEATURE REQUEST] Sega Genesis Overclocking (and perhaps others)

### ISSUE THREAD

**Issue by Blackgrowl** [jsgroth/jgenesis#133]
Hello, one thing I have noticed that almost every Genesis emulator misses is the ability to overclock it. More specifically, to emulate an overclock, after all you're actually not overclocking the system itself, you emulate it...And you also emulate the overclock.

Genesis is powerful, but sometimes it needs more "juice", same with NES, SNES and so on.

I can give an example of a game that would benefit with overclocking; Ranger X.
In Ranger X, when you start the game and destroy one of those big holes that spawn enemy robots, there will be quite a slow down after the explosion.

Of course, also adding the ability to emulate overclock on the other systems, be it also Sega CD and 32X or NES and SNES that this emulator also emulates, would be nice.

I would recommend to take a look at Mesen to see how they do overclocking emulation for their NES and SNES.

**Comment by jsgroth** [comment]
This is definitely something I'd like to implement! I've read a bit about how newer NES and SNES emulators implement CPU overclocking and the same trick should work for Genesis + Sega CD + 32X as well.

Writing this out mostly for posterity, my understanding is that newer NES/SNES emulators implement overclocking by inserting additional virtual scanlines at the end of the active display period, right before vertical blanking begins. During these virtual lines the emulator runs _only_ the emulated CPU without running any of the other emulated components (e.g. video/audio processors). This has the effect of running the CPU X% faster relative to the rest of the console but it has much higher compatibility than running it X% faster all the time, since a lot of games have mid-frame raster effects that will break if the CPU isn't running at exactly the right speed.

It looks like Mesen also has the option to insert some virtual scanlines immediately _after_ vertical blanking begins, I guess because some games don't benefit from overclocking only during active display.

Genesis does have two CPUs but I don't think there's much reason to overclock the Z80 since most games only use it for audio processing, and overclocking it would likely break any sound effects or music tracks that use the YM2612's DAC channel (which usually rely on carefully timed Z80 code). I'll have to play around with it though.

**Comment by Blackgrowl** [comment]
Sorry, I know nothing about Genesis hardware, but you say the Z80 is a CPU that's used mostly for sound, there really is no reason to overclock it other than perhaps for some very specific reasons that I can't find any.

However, the other CPU which I guess it works just like NES and SNES does (it controls the whole console) sure would benefit greatly from an overclock.

I'm willing to try a test version to tell you if it works in Ranger X fine or not if need be.

**Comment by jsgroth** [comment]
Right, the main Genesis CPU is a 68000, and pretty much every game uses the 68000 for game logic and video processing as well as programming/commanding the Z80. Any game with slowdown should benefit from overclocking the 68000.

I'm not sure when exactly I'll get to this but I'll note on the issue when I have a version of this working.

**Comment by Blackgrowl** [comment]
Funnily enough I know about the 68000 because of the Commodore Amiga.

With that in mind, I think emulating an overclocked 68000 may be a bit complicated, but since it's only the 68000 it is a bit easy.
I know one emulator that uses it and can overclock it, it's WinAUE, but the way it does it is very customizable, such as...Making it emulate as accurately as possible to the 68000's real timings, or just emulating it as fast as it theoretically can get.

I doubt the Genesis would need that, something like 2x, 4x and even 8x will be enough for it.

**Comment by jsgroth** [comment]
Implementing overclocking using virtual scanlines ended up being a bit complicated because of how DMA and video memory access work on the Genesis, so I haven't done that yet, but I did try implementing a more crude form of overclocking in the form of adjusting the 68000's master clock divider. This gives a selection of 7 different clock speeds ranging from ~7.67 MHz (actual hardware speed) to ~53.69 MHz (Genesis master clock frequency), with more options on the lower end of speed.

Overclocking this way seems to work well in some games but is quite broken in others, e.g. it screws up the music tempo in Sonic 2 and 3 (though it's possible that would happen even with more intelligent overclocking). Some games seem to work ok with moderate overclocking but break if the divider is set lower than 3 or 4 (13-18 MHz clock speed).

I'm not sure where I'll stick this permanently, but for now I added a widget to the general Genesis settings window for adjusting this:
![divider-widget](https://github.com/user-attachments/assets/5ee60bed-3001-4208-a152-39d2ceaf7ce3)

Builds are available here if you'd like to test for yourself:
https://github.com/jsgroth/jgenesis/actions/runs/11450181845

**Comment by Blackgrowl** [comment]
I have given it a try, just did it the "brutal" way by simply having it divide to 1, so I was playing at a whooping 53mhz, and I've got great news; it works fantastic!

I've tried it on Ranger-X, there are no more slowdowns when I explode one of those robot-maker machines.
Tried it on Urban Strike, the game was silky smooth, this game tends to have slowdowns.
As well as tried it on the infamous port, "Soldiers of Fortune", where slowdowns were a given. VERY SMOOTH! The fact it made Soldiers of Fortune have 0 drops is fantastic.

One side effect I did notice, and is to be expected, is that my CPU was a bit more heaty than usual. Not too much though, it reached 69c at max and this is on the "Soldiers of Fortune" game, on the other two it was a bit lower.

I hope you can find a way to further improve it, though the way it is right now is great enough, I see no problem with keeping it as is, even if you say that the current overclock isn't exactly good, well the GUI sure is beautiful at least.

Also, I've tried it again, set it to 3 in Soldiers of Fortune, it runs without issues. Makes sense, simply doubling the CPU speed is enough for any game ,even SoF.

**Comment by jsgroth** [comment]
That's good to hear that it works well with those games! I tested mostly with games that I know are sensitive to CPU timing, and results were mixed, but even with those timing-sensitive games there were some where decreasing the clock divider worked really well (e.g. Panorama Cotton, which _constantly_ slows down on actual hardware but runs really smoothly with a divider of 4 or 5).

I'm unfortunately not very surprised that host CPU usage was very high with Soldiers of Fortune. That's one of the few Genesis games that frequently stalls the 68000 by writing to VRAM during active display, and the way I emulate those stalls is currently very inefficient (and this game specifically actually depends on those CPU stalls to render its graphics correctly). It's not that big of a deal when running at actual hardware speed but it really slows things down when overclocking the 68000. However, as you noticed, running at 53 MHz is nowhere near necessary to fix slowdown in hopefully any game - I'll probably adjust the help text to note that a clock divider lower than 3 or 4 should not be necessary and will significantly increase the emulator's CPU usage.

Anyway, the 68000 overclocking as-implemented will go into the next release. I still want to investigate overclocking via virtual scanlines to see if that works any better with the games that have issues with divider-based overclocking, but it sounds like the current implementation improves enough games that it's worth leaving it in.

**Comment by jsgroth** [comment]
This is included in the latest release, and I opened #138 for possible future improvements.

**Comment by Blackgrowl** [comment]
> This is included in the latest release, and I opened #138 for possible future improvements.

Fantastic, I like the idea of using virtual scanlines, Mesen uses the same method and it's better than the overclock I've noticed in other emulators.
