### ISSUE TITLE
Problem with the inputs; key input is strictly specific

### ISSUE THREAD

**Issue by Blackgrowl** [jsgroth/jgenesis#139]
Hello, I've setup my Save States to be going from F1 to F8, to load I set it up so it's Left Shift + Fx.
Only one problem; sometimes, I also use the Right Shift, but sadly it seems that jgenesis' inputting is strict, it has to be the Left Shift or else.

Is there any way I can make it use either Left or Right Shift?

Picture for reference if needed:
![image](https://github.com/user-attachments/assets/7cbbcee3-e8c4-4f3e-98db-66adcefd5076)

**Comment by jsgroth** [comment]
This happens because keyboard mapping currently uses the SDL keycode directly, and SDL gives different keycodes to Left Shift and Right Shift because they're different physical keys on the keyboard. I agree that this is very unintuitive for modifier keys (Shift/Ctrl/Alt) - I can change it so that the emulator doesn't distinguish between left and right shift, and they're both just treated as Shift (and same for Ctrl and Alt mappings).

As a temporary workaround you could use Input Mapping \#&#8203;2 to create a second mapping of Right Shift + Fx for each of these hotkeys so that either left or right shift will trigger the hotkey, but I do plan to fix this so that won't be necessary forever.

**Comment by Blackgrowl** [comment]
> This happens because keyboard mapping currently uses the SDL keycode directly, and SDL gives different keycodes to Left Shift and Right Shift because they're different physical keys on the keyboard. I agree that this is very unintuitive for modifier keys (Shift/Ctrl/Alt) - I can change it so that the emulator doesn't distinguish between left and right shift, and they're both just treated as Shift (and same for Ctrl and Alt mappings).
> 
> As a temporary workaround you could use Input Mapping #​2 to create a second mapping of Right Shift + Fx for each of these hotkeys so that either left or right shift will trigger the hotkey, but I do plan to fix this so that won't be necessary forever.

Thank you, glad to know you will be fixing it.
The temporary solution will serve for now, I really love this emulator and I hope to see it improve more and more over the years.

**Comment by jsgroth** [comment]
This is fixed in v0.8.3. Existing input mappings using Left Shift or Right Shift will be automatically converted to just Shift, and same with Ctrl/Alt mappings.
