### ISSUE TITLE
Make jgenesis run .rar files

### ISSUE THREAD

**Issue by Blackgrowl** [jsgroth/jgenesis#142]
Just a little suggestion, since I think after update 0.8 or 0.8.1, jgenesis is capable of running .7z and .zip files, why not also .rar?

**Comment by jsgroth** [comment]
Each archive format requires a bit of additional work to support. For reference, I added ZIP and 7Z support for #91.

One potential issue with RAR specifically is that it's a proprietary format that uses a proprietary compression algorithm. ZIP and 7Z are both open formats that (by default) use open compression algorithms like DEFLATE (.zip) and LZMA/LZMA2 (.7z default).

There's a source-available library for RAR decompression (unrar) that might be usable - its [license](https://github.com/muja/unrar.rs/blob/master/unrar_sys/vendor/unrar/license.txt) restricts using the source code to reverse engineer the RAR format or compression algorithm, but it otherwise seems to allow free use in other applications. Although given point 6 in that license, If I did use that library then I'd be inclined to build without RAR support by default.

**Comment by Blackgrowl** [comment]
I see, I was expecting that there'd be some license-based difficulties with RAR, so I was curious about it. Thanks for explaining.

For better info, I don't mind that jgenesis has no RAR support, I just extract the rom and that's it.

**Comment by jsgroth** [comment]
Thanks for the additional info, that's good to know. After looking over the options here I've decided that I'm not going to implement RAR support, at least not any time soon. 7Z provides comparable compression and isn't burdened by licensing issues.

All of the source-available RAR decompression libraries I could find either use unrar with the license restriction or don't support the latest version(s) of RAR, so adding RAR support without taking on the license restriction would be quite a lot of work.
