### ISSUE TITLE
Appimage Support

### ISSUE THREAD

**Issue by mrdeathjr28** [jsgroth/jgenesis#20]
Hi if can possible add appimage will be great

thanks

**Comment by jsgroth** [comment]
Sure, I can look into this. I agree that an AppImage package would be nicer for Linux than a standalone binary.

**Comment by jsgroth** [comment]
The GitHub Actions workflow is now building AppImage packages on every commit, starting here:
https://github.com/jsgroth/jgenesis/actions/runs/8759009868

I'll also publish AppImage packages with the next release tag which will probably be soon.

These packages are built on Ubuntu 22.04 so they may not work on older Linux distros. Unfortunately I can't build on Ubuntu 20.04 because the SDL2 version is too old, the code won't compile.

**Comment by jsgroth** [comment]
The latest release includes published AppImage builds:
https://github.com/jsgroth/jgenesis/releases/tag/v0.7.1
