### ISSUE TITLE
jgenesis-config.toml not taken into account when running from cli

### ISSUE THREAD

**Issue by Tartifless** [jsgroth/jgenesis#24]
Hello,
Is there a way to use the settings defined within the "jgenesis-config.toml" when running the -cli executable ?

**Comment by jsgroth** [comment]
This is not currently possible. As you've noticed, input configuration in the CLI is currently extremely limited (to be honest, I'm a little surprised to see someone other than me trying to use it).

It would be pretty easy to make the CLI able to read the GUI's input configuration from jgenesis-config.toml, although that might be somewhat confusing if it's not reading _all_ configuration from there (which would be a little more complex). It would also be easy to add a command line arg to the GUI to automatically open a specific game file at startup, as you suggested.

**Comment by Tartifless** [comment]
Hi,
Thanks for the answer, from my point of view both would work, as I can manage either to update settings in the toml file through my launcher build in c#.

Both would be a nice addition and would enable integration with our front-end.

**Comment by jsgroth** [comment]
I implemented the GUI arg first because that was simpler. Dev builds are available here:
https://github.com/jsgroth/jgenesis/actions/runs/8901751196

There's a new optional `-f/--file-path` arg that, if set, will immediately launch the specified file after the GUI is initialized and then close the GUI when the emulator window is closed. If there is an initialization error (e.g. file doesn't exist) then the GUI will log an error and immediately exit.

I would still like to fix this for the CLI as well, because there's not really any reason to have the GUI window running in the background if it's not going to be used.

**Comment by Tartifless** [comment]
I'll test tomorrow and report back if I notice any issue.

**Comment by Tartifless** [comment]
Works fine thanks a lot

**Comment by Tartifless** [comment]
Hello,
I still have an issue with this : when running the gui executable with a game starting automatically, the game windows does never get the focus, making it mandatory to click with the mouse to be able to use the controller.
Windows 11, tested on windows 10 also.

It seems that the emulator gui window appears and steels the focus.
@jsgroth

**Comment by jsgroth** [comment]
Ah, I only tested on Linux before - I see the same behavior with this flag on Windows 10. I'll see if I can fix it by waiting to launch the emulator until after the first GUI paint.

**Comment by jsgroth** [comment]
I don't have a Windows 11 machine to test on, but waiting until after the first full GUI paint fixed this on Windows 10 for me. Builds here:
https://github.com/jsgroth/jgenesis/actions/runs/8931723133

**Comment by Tartifless** [comment]
Thanks, I'll test later today when coming home from work.
Win11 has some strange behavior with focus since they implemented multi-tabs in explorer, however there is no reason it would act differently than win10.

**Comment by Tartifless** [comment]
Hello: working fine on windows 11 also

**Comment by jsgroth** [comment]
I just pushed a change that has the CLI read all configuration from the GUI's config file, including input configuration:
https://github.com/jsgroth/jgenesis/actions/runs/9022312465

By default the CLI uses the same config file path as the GUI, and there's also an optional `--config` arg to override the config path.

Most of the previously-existing args are still present but they now function as temporary config overrides rather than being the only way to configure the CLI.

**Comment by Tartifless** [comment]
Awesome.
So the arguments have the priority over the config from what I read, right ?
That's great, will test this when I am back from holiday.

**Comment by jsgroth** [comment]
That is correct, the CLI args have priority over the config file if they are set.
