### ISSUE TITLE
[Feature request] support for nes zapper

### ISSUE THREAD

**Issue by Tartifless** [jsgroth/jgenesis#25]
Hello,
In the same way support for the Superscope is enabled, it would be great to have support for the NES zapper.
I don't know if you have a feature request somewhere or a forum of some sort.

Regards.
Ben

**Comment by jsgroth** [comment]
No, I don't have a forum or anything. Opening issues here is fine for feature requests / bug reports.

At a glance the Zapper doesn't seem _too_ hard to emulate (and I can re-use parts of my Super Scope code for reading mouse inputs), but almost everything NES-related ends up being more complicated than I expect so we'll see.

**Comment by jsgroth** [comment]
The Zapper is now supported on master. Tested with NTSC and PAL as well as different overscan settings to make sure the mapping from mouse position to NES pixel position is correct.

The Zapper's light sensor is a bit nondeterministic on actual hardware because its precise behavior depends on the strength of the TV's light beam and how the TV displays particular colors. Zapper games don't seem to depend on that though, only that the sensor detects very bright colors (e.g. white) and doesn't detect very dark colors (e.g. black).
