### ISSUE TITLE
Warriors of Might and Magic (USA) (En,Fr,De).gbc HUD is corrupt

### ISSUE THREAD

**Issue by benderscruffy** [jsgroth/jgenesis#30]

**Comment by jsgroth** [comment]
Caused by a window bug: the game enables the window near the bottom of the screen, but the window shouldn't display because WY=0 and the window was disabled for the entire first line.

Fixed this and also re-tested [fairylake.gb](https://github.com/Hacktix/scribbltests/tree/master/fairylake) and Pokemon GSC which depend on somewhat obscure window behaviors.
