### ISSUE TITLE
Altered Space - A 3-D Alien Adventure (USA).gb missing sound fx during gameplay

### ISSUE THREAD

**Issue by benderscruffy** [jsgroth/jgenesis#32]

**Comment by jsgroth** [comment]
This game seems to depend on the initial contents of wavetable RAM at power-on rather than populating RAM with its own audio samples:
https://gbdev.gg8.se/wiki/articles/Gameboy_sound_hardware#Power_Control

Interestingly, this also means that the sound effects are different when played on a Game Boy vs. Game Boy Color. They sound way too high-pitched with the GBC initial values.
