### ISSUE TITLE
Demotronic Final Demo (PD) [C].gbc doesnt detect it as a gameboy

### ISSUE THREAD

**Issue by benderscruffy** [jsgroth/jgenesis#34]

**Comment by jsgroth** [comment]
This depends on an obscure wavetable RAM behavior that no officially licensed games depend on (as far as I know): if the CPU reads from wavetable RAM while the wavetable channel is playing, the read should return the byte at the channel's current position rather than returning the byte at the requested address. Demotronic doesn't seem to require extremely precise timing like dmg_sound and cgb_sound do, only the behavior.

The demo mostly works after fixing that, but the timing seems to be slightly off for the mid-scanline SCY writes in the first effect - it looks like they're taking effect one tile too early. The seams are in the wrong positions:

![Screenshot from 2024-05-06 16-03-02](https://github.com/jsgroth/jgenesis/assets/1137683/3b367020-937b-492d-b6f2-e58190e4918a)

**Comment by jsgroth** [comment]
Latching SCY and SCX 2 dots before the BG tile fetch fixes the effect:
![Screenshot from 2024-05-07 12-47-34](https://github.com/jsgroth/jgenesis/assets/1137683/0bc0a67d-e00d-4777-9ffa-821808377485)
