### ISSUE TITLE
GBVisualizer doesnt show the oscillation wave

### ISSUE THREAD

**Issue by benderscruffy** [jsgroth/jgenesis#36]
[visualizer.zip](https://github.com/jsgroth/jgenesis/files/15211630/visualizer.zip)
https://github.com/LIJI32/GBVisualizer

**Comment by jsgroth** [comment]
This depends on the (officially) undocumented PCM12 and PCM34 registers, which I hadn't previously implemented. I went ahead and implemented these because they're trivial to emulate - they simply expose the current APU channel outputs as 0-15 values.

I noticed a separate issue with this demo which is that the music starts playing immediately. Based on other emulators (e.g. SameBoy and Emulicious) there should be a short pause after boot before the music starts playing. This was caused by not initializing HRAM the same way that the CGB boot ROM does, which is also now fixed.
