### ISSUE TITLE
Graphical glitch in homebrew demo: MENTAL RESPIRATOR

### ISSUE THREAD

**Issue by benderscruffy** [jsgroth/jgenesis#41]
"Gin&Tonic drink" effect is not correct
[Mental Respirator by Phantasy (PD) [C].zip](https://github.com/jsgroth/jgenesis/files/15211655/Mental.Respirator.by.Phantasy.PD.C.zip)

**Comment by jsgroth** [comment]
This seems to be caused by a combination of mid-scanline SCX writes taking effect too early (probably same issue as the Demotronic bug in #34) as well as possibly the LY=LYC STAT interrupt triggering too early when LYC=0.

**Comment by jsgroth** [comment]
While some of the info in this doc is outdated/incorrect, the LY=LYC section does support that the LY=LYC STAT interrupt triggers later than I currently have it triggering in the LYC=0 case:
https://github.com/geaz/emu-gameboy/blob/master/docs/The%20Cycle-Accurate%20Game%20Boy%20Docs.pdf

There also seems to be an additional short delay when the CPU is in double speed mode, which it is here. Implementing this delay combined with the fix for #34 fixes this effect (there were previously noticeable artifacts on the right side of the screen):
![Screenshot from 2024-05-07 13-05-59](https://github.com/jsgroth/jgenesis/assets/1137683/8dcaa31a-c6dc-4993-9700-e405d7f6d631)
