### ISSUE TITLE
Worms Armageddon (USA) (En,Fr,Es).gbc choose quickstart and game will freeze up

### ISSUE THREAD

**Issue by benderscruffy** [jsgroth/jgenesis#44]

**Comment by jsgroth** [comment]
This was a pain to figure out, but I believe I have this game working properly now.

First, it depends on the fixes for both #35 (HDMAs initiated during HBlank should begin immediately) and #37 (HBlank STAT interrupts should not block LY=LYC STAT interrupts).

Second, there were some bugs in handling LYC=0, most significantly that the LY=LYC bit in the STAT register was getting set way too late. It should get set at the same time that LY changes from 153 to 0 (which happens early in scanline 153), but it wasn't getting set until scanline 0. Fixing this got the game to not immediately freeze after starting a game, but it would usually crash within a few seconds due to executing an illegal opcode.

The final issue is that this game doesn't expect WRAM to be _fully_ randomized when the game boots. In actual hardware, the CGB boot ROM zerofills WRAM bank 2 before jumping to the cartridge's entry point. This game breaks horribly if the contents of WRAM bank 2 are randomized instead of zeroed. The other 28KB of WRAM can be randomized, just not bank 2.
