### ISSUE TITLE
Space Waste Demo by Octarine crashes out on the first part of the demo

### ISSUE THREAD

**Issue by benderscruffy** [jsgroth/jgenesis#48]
[oct-spw.zip](https://github.com/jsgroth/jgenesis/files/15211974/oct-spw.zip)

**Comment by jsgroth** [comment]
Timing issue: The demo does a whole bunch of mid-frame CGB palette writes that are each gated by `STAT & 2 == 0`, and it needs them all to finish before scanline 130 or it will miss an expected LY=LYC interrupt. This ultimately causes it to crash: it unexpectedly handles a STAT interrupt while handling a VBlank interrupt, and then it returns to the VBlank interrupt handler with the wrong MBC5 ROM bank set and goes off the rails.

Similar in spirit to the fix for #29, having the CPU read the mode 0->2 transition in STAT one M-cycle later fixes this and gets the demo to run to completion.
