### ISSUE TITLE
flowing_palette.nes crashes out straight away

### ISSUE THREAD

**Issue by benderscruffy** [jsgroth/jgenesis#53]
[flowing_palette.zip](https://github.com/jsgroth/jgenesis/files/15246736/flowing_palette.zip)

**Comment by jsgroth** [comment]
The crash is caused by incorrectly parsing the iNES ROM header. The emulator is currently unconditionally using NES 2.0's additional bits for PRG ROM size and CHR ROM size when it should only use them if the ROM header identifies itself as NES 2.0.

(I also consider it a major bug that the emulator crashes instead of showing an error when this happens and will fix that very shortly)

Once the ROM loads, it shows a blank screen because of the same bug as #55.
