### ISSUE TITLE
full_palette.nes nothing but a black screen

### ISSUE THREAD

**Issue by benderscruffy** [jsgroth/jgenesis#55]
[full_palette.zip](https://github.com/jsgroth/jgenesis/files/15246863/full_palette.zip)

**Comment by jsgroth** [comment]
I believe this is caused by incorrectly handling the behavior of how the PPU chooses what color to display when rendering is disabled (PPUMASK & 18 == 0). This test leaves rendering disabled and expects to be able to change the displayed color by changing PPUADDR to point to different addresses in palette RAM.
