### ISSUE TITLE
VOXEL.smc demo crashes out

### ISSUE THREAD

**Issue by benderscruffy** [jsgroth/jgenesis#62]
[VOXEL.zip](https://github.com/jsgroth/jgenesis/files/15247487/VOXEL.zip)

**Comment by jsgroth** [comment]
Ignoring the highest PBR/ROMB bit on memory accesses fixes this from crashing, but the demo doesn't work correctly:
![Screenshot from 2024-05-08 13-33-03](https://github.com/jsgroth/jgenesis/assets/1137683/95ed8a34-0033-4e7d-9fa1-55de8efbe707)

This likely requires the fixes described in this ares issue:
https://github.com/ares-emulator/ares/issues/436

**Comment by jsgroth** [comment]
This is fixed after implementing the following:
* Mask out the highest bank bit in all Super FX GSU memory accesses
* More robust handling of non-power-of-two ROM sizes that is now used with all cartridge types except for SPC7110
* The Super FX code now detects this demo and gives it 64KB of cartridge RAM instead of the default of 32KB (which is used for Star Fox)

![Screenshot from 2024-05-12 15-30-14](https://github.com/jsgroth/jgenesis/assets/1137683/a88167ed-b2fd-4a94-953b-82a2775de65b)
