### ISSUE TITLE
Add support for launching ZIP-compressed files

### ISSUE THREAD

**Issue by leonstyhre** [jsgroth/jgenesis#91]
Hi!

Would it be possible to add support for launching ZIP archives, and perhaps 7Z archives as well?
Unless I've missed something I need to manually unzip each game before I can run it in jgenesis?

I have only tested on Linux using the CLI AppImage.

Many thanks in advance!

**Comment by jsgroth** [comment]
You haven't missed anything - the emulator doesn't currently support loading compressed files aside from CHD images of Sega CD discs, regardless of platform or which frontend you're using.

It should be simple to support the most basic case of .zip files that contain a single ROM image, and .7z should be doable as well. Supporting archives that contain multiple images is slightly trickier but still doable - the backend piece of the emulator just needs to receive the path to the image within the .zip file in addition to the path to the .zip file.

The one thing I probably won't support is loading Sega CD CUE/BIN disc images out of compressed archives, which is not really practical because of how that disc format works.

**Comment by leonstyhre** [comment]
Thanks for the clarification, and yes it would be great if you could add ZIP and 7Z support! As for .bin/.cue this is mostly obsolete now anyway when there are CHD files, and even more so to put such files inside a ZIP archive.
Thanks! :)

**Comment by leonstyhre** [comment]
Hi, any progress on this issue? I have just added support for jgenesis for a lot of systems in ES-DE for the upcoming 3.1.0 release but I'm pretty sure many people will believe the emulator is broken as it can't currently launch zipped games.

https://gitlab.com/es-de/emulationstation-de/-/commit/fb0ab444697f53048a0ebfd3973668e2f354d51e

Thanks in advance :)

**Comment by jsgroth** [comment]
Hi, the emulator currently supports loading from both ZIP and 7Z files on master but I haven't published a release with these changes yet. I haven't had much time to work on this project recently but I would like to publish a new release soon, hopefully early this week.

I haven't yet implemented good handling for archives containing multiple ROM images (the emulator will attempt to load the first file with a supported file extension), but loading from single-file archives should work on master and will be in the next release.

**Comment by leonstyhre** [comment]
Thanks for the info, that's great news! I think supporting a single file per archive is a very good start as that's how many people package their games for older consoles. You could argue how much space you actually save by doing this, but it's still a common practice. Looking forward to the release and to have jgenesis support in ES-DE for ~15 systems!

**Comment by jsgroth** [comment]
It came a bit later than early last week because I found some bugs as I started testing more comprehensively, but I just published a release that includes the aforementioned changes for loading from .zip/.7z:
https://github.com/jsgroth/jgenesis/releases/tag/v0.8.0

**Comment by leonstyhre** [comment]
That's great, thanks for this! I just tested the AppImage and my zipped games launched perfectly :)

So I'm closing this issue, thanks again!
